Maitreyee/aabb
NextDroid/PotreeConverter pull request #29
Opened 2021-06-02 21:35 UTC by maitrejoshi

Use easting/northing bounds from VTM calculation (+ appropriate padding) to seed potreeconverter AABB input parameter -- speeds up processing significantly. Will need to determine bounds for z.

2021-06-03 18:47 UTC, bcasselsND approved these changes

2021-06-04 14:30 UTC, arjunskND requested changes

2021-06-04 14:30 UTC, arjunskND commented on PotreeConverter/src/main.cpp
> +		double paddingVTM = 300;
define `paddingVTM` on the top of the file, like so `constexpr double PADDING_VTM = 300;`

2021-06-04 14:30 UTC, arjunskND commented on PotreeConverter/src/main.cpp
> +		double paddingAltitude = 100;
Let's get rid of `paddingAltitude`, just use `PADDING_VTM` for all northing easting and altitude.

2021-06-04 14:30 UTC, arjunskND commented on PotreeConverter/src/main.cpp
> +        double maxNorthingAdjusted  = vtmMetadata.maxNorthing + paddingVTM;
Clean this indentation up. Match the indentation with other parts of the file. Sometimes it is tab vs. space.

2021-06-07 13:16 UTC, arjunskND approved these changes

2021-06-07 13:16 UTC, arjunskND commented on PotreeConverter/src/main.cpp
> +        auto vtmMetadata = parseVTMmetadata(a.metadataProcessingFile);
You left the indentation of this one hanging.

2021-06-18 17:15 UTC, arjunskND commented on PotreeConverter/src/main.cpp
> +
@maitrejoshi , can you fix this please?

2021-06-18 17:23 UTC, merged